### ISSUE TITLE
cli: Fix babel configuration

### ISSUE THREAD

**Issue by ernscht** [namics/frontend-defaults#10]
Using babel >=7 we have to use the scoped names `@babel/env` or `@babel/preset-env` instead of `env` 
"presets": [
	"@babel/preset-env"
]

and even better:
It would make sense to use `babel.config.js` instead of `.babelrc`. This allows a more flexible configuration.

Example babel.config.js:
```
module.exports = {
	presets: [
		[
			require.resolve('@babel/preset-env'),
			{ useBuiltIns: 'entry' },
		]
	],
	plugins: [...],
};
```

**Comment by smollweide** [comment]
related issue: https://github.com/namics/webpack-config-plugins/issues/48

**Comment by ernscht** [comment]
The original issue is fixed. 👍
I wonder if this might make sense:
* moving @babel/polyfill to dependencies (instead of devDependencies)
* adding browserslist in package.json could also mean installing the package itself.
* If we include "preset-react" in the babel configuration, it might also make sense to use some plugins such as @babel/plugin-proposal-decorators or @babel/plugin-syntax-dynamic-import? (minimum configuration or as many examples as possible?)

**Comment by smollweide** [comment]
decorators and dynamic-import added
