### ISSUE TITLE
Improve linting dev expirience

### ISSUE THREAD

**Issue by jantimon** [namics/frontend-defaults#12]
We have great linting presets which guide developers into the right direction and prevent human errors.

Unfortunately the amount of "disable-next-line" comments increased a lot in many projects where linters are used.

For me that is a symptom that something about our linters does not work the way we intended it.  
In my opinion we should use "disable-next-line" similar to complex scss mixins and loops.  
It's fine for abstract utils but should not be used in our day to day work.

I would like to discuss one lint rule as an example but it might also be true for other lint rules.  
Many projects contain the following code:

```js
console.log('debug', valueX); // eslint-disable-line
```

So if this rule has to be disabled so many times why do we have it in our defaults anyway?  
The idea behind this rule is that we don't want to have `console.log` statements in our **merged** code.

In our projects we have the following four quality gates:

1. ide & dev build
2. precommit
3. git server received push
4. manual code review

For me it seems like that linting for `console.log` in **step 1** causes issues for most developers so they disable it while fiddeling around with their code to find a good way to implement a feature or to debug a bug.
However disabling the linting rule moves it to **step 4** which is a manual task of a second person.

What do you think about moving it to **step 2** or **step 3**?  

We might achieve that with two configs:

`.eslintrc.json` (for **step 1**) without the `console.log` rule or `console.log` as warning
`.eslintrc.strict.json` (for **step 2** or **step 3**) which extends `.eslintrc.json` and adds the `console.log` rule as error

**Comment by LOK-Soft** [comment]
This sounds quite promising to me.

**Comment by janbiasi** [comment]
Sounds great, looks like a nearly perfect solution 👍

**Comment by smollweide** [comment]
Implemented as @jantimon described.

<img width="536" alt="2019-07-18_0800" src="https://user-images.githubusercontent.com/2912007/61433272-1d35c480-a933-11e9-9a02-64509a2bdb3e.png">

The rules in `.eslint.js` are just for IDE. `npm run lint` and `lint-staged` using `.eslint.strict.js`

**Comment by janbiasi** [comment]
Awesome! Thank you 🔥

**Comment by jantimon** [comment]
Really cool 👍
