### ISSUE TITLE
Add stylelint-scss

### ISSUE THREAD

**Issue by jantimon** [namics/frontend-defaults#16]
Have you considered to add the stylelint plugin [stylelint-scss](https://github.com/kristerkari/stylelint-scss)?

It allows to disallow scss code like the following:

```
.class {
  &-union {
//↑
// This type usage of `&`
  }
}
```

https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/selector-no-union-class-name/README.md

**Comment by ernscht** [comment]
I also liked the idea very much. I tried it recently. 
But I only had problems (especially in combination with our current rules and plugin usage). And I was afraid to check if it is fixable.

**Comment by smollweide** [comment]
kristerkari/stylelint-scss#345

is solved. Can we add stylelint-scss?

**Comment by ernscht** [comment]
I'll make a suggestion

**Comment by ernscht** [comment]
released in 0.4.0
