### ISSUE TITLE
pretty-quick validates wrong files

### ISSUE THREAD

**Issue by LOK-Soft** [namics/frontend-defaults#18]
Pretty-quick gets called without additional parameters package.json, so all staged files will be validated, even if they are not supposed to be.
Either there should be the additional pattern parameter or even better since lint-staged is used just use `prettier --write` as it is done in the script section of package.json

**Comment by smollweide** [comment]
Hi @LOK-Soft,
thank you. We will remove pretty-quick because lint-staged now also solves the issue we had with prettified files wich are not staged.

**Comment by smollweide** [comment]
should be fixed with `npx @namics/frontend-defaults-cli@0.5.1`
