### ISSUE TITLE
Outdated stylelint-scss dependency

### ISSUE THREAD

**Issue by dhardtke** [namics/frontend-defaults#23]
Hey there,

we are using `@namics/stylelint-config` in our project at Namics and noticed `npm` is logging a warning upon executing `npm install`:

> npm WARN stylelint-scss@3.13.0 requires a peer of stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 but none is installed. You must install peer dependencies yourself.

This happens because `@namics/stylelint-config` depends on `stylelint-scss` 3.13.0 which does not support the latest `stylelint` yet.

Would it be possible to update the dependency to the latest version of `stylelint-scss`?

Thanks :)

**Comment by ernscht** [comment]
Many thanks for your input.
We will release a new package this week.

**Comment by ernscht** [comment]
released as @namics/stylelint-config@1.0.0
