### ISSUE TITLE
ts-config: add TypeScript 4 compatibility

### ISSUE THREAD

**Issue by ernscht** [namics/frontend-defaults#29]
Because TypeScript has been available in version 4 for some time, we should also make the configuration compatible.

**Comment by prothweil** [comment]
Hi,
I opened a PR (#30 ) for this issue.
I tested the config with a few projects, didn't find any conflicts. 
None of the applied rules are deprecated either, so compatibility looks good so far.

**Comment by ernscht** [comment]
published as @namics/ts-config 1.1.0

and thanks for your work
