### ISSUE TITLE
prettier: A change in prettier causes problem in the recommendation of usage with lint-staged

### ISSUE THREAD

**Issue by ernscht** [namics/frontend-defaults#6]
Our [usage recommendation for prettier-config with lint-staged](https://github.com/namics/frontend-defaults/blob/master/codequality/prettier/README.md#we-recommend-to-use-prettier-together-with-lint-staged-and-husky) does not work anymore with prettier 1.15.3. 
[In 1.15.3 they changed the status code to "0"](https://github.com/prettier/prettier/pull/5512) in any case using the options `--write` and `--list-different` together. This leads to the fact that the commit now works despite errors. Another commit must therefore be appended. ([discussion](https://github.com/prettier/prettier/issues/4144))

The solution worked perfect before ;-)
I'm unsure what we should do now.

I don't really like these ideas:
- downgrade to prettier 1.15.2
- adding `git add` to "lint-staged" config
- using `--list-different` only will prevent the commit, but won't give us meaningful feedback

Any ideas?

**Comment by jantimon** [comment]
A possible workaround which is not as good as `prettier 1.15.2` is the following:

```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "pretty-quick --staged"
    ]
  },
```

It requires:  

```
   "husky": "1.3.1"
    "lint-staged": "8.1.0"
    "prettier": "1.15.3"
    "pretty-quick": "1.8.0"
```

It will prettify even partial staged files correctly and commit them correctly.

However it does not allow to see the changes prettier did.

**Comment by smollweide** [comment]
`pretty-quick` will fix our problem with unwanted changes which are not part of the commit right?

**Comment by jantimon** [comment]
It is solved by the latest `lint-staged` version.

`pretty-quick` does `git add` under the hood so we don't have to do that manually.

**Comment by jantimon** [comment]
By now `pretty-quick` does not work if `.prettierignore` is not in the repository root.  
So we should probably not use it until https://github.com/azz/pretty-quick/issues/14 is fixed

**Comment by jantimon** [comment]
azz/pretty-quick#14 is fixed - `pretty-quick` now supports `.prettierignore` for the working directory too.
