### ISSUE TITLE
prettier: Fails to parse md files

### ISSUE THREAD

**Issue by jantimon** [namics/frontend-defaults#7]
The default parser is set to typescript without any overwrite for md files.

https://github.com/namics/frontend-defaults/blob/cc10f74c37444cafb0d27c6c206be5b375bc0df6/codequality/prettier/index.js#L11

Unfortunately this causes the following error:

```
SyntaxError: Invalid character. (1:1)
> 1 | # Hello World
    | ^
  2 | 
  3 | Lorem ipsum
  4 | 
at e (node_modules/prettier/parser-typescript.js:1:329)
```

**Comment by smollweide** [comment]
Hi Jan,
use the recommended config

```
"prettier": "prettier --write \"**/*.*(js|jsx|ts|tsx|json)\""
```

md should not be prettified

**Comment by ernscht** [comment]
This is well known. There is also no configuration for css and scss. 
This is because we couldn't find a good configuration for Markdown and css/scss.
The way we go for now ist to restrict the filetypes for prettifying:

`"prettier": "prettier --write \"**/*.*(js|jsx|ts|tsx|json)\"",`

**Comment by ernscht** [comment]
we don't use `pretty-quick` til now - why you want to use it?

**Comment by jantimon** [comment]
It solves #6 and is the recommended prettier husky integration according to the getting started section of https://prettier.io/
